### ISSUE TITLE
diff_drive_controller is not working

### ISSUE THREAD

**Issue by ChVictoria** [KPI-Rover/ros_sw#9]
When i run the project as described in the Readme, i can't move the robot with teleop_twist_keyboard. Messages are published to the /diff_drive_controller/cmd_vel topic as expected, but there is no diff_drive_controller node in the rqt graph, and it seems like Gazebo doesn't see that topic. Tried adding a bridge as follows:

- ros_topic_name: "diff_drive_controller/cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.TwistStamped"
  direction: ROS_TO_GZ

doesn't work either.
@Fastroof 

![Screenshot from 2024-11-09 13-07-24](https://github.com/user-attachments/assets/4be020d3-4857-4ff4-9dc8-c5268fe856c8)
![Screenshot from 2024-11-09 13-33-28](https://github.com/user-attachments/assets/bf2c0f71-6570-4ec8-88eb-85b5486fdf0e)

**Comment by ChVictoria** [comment]
Solved. Installed ros-jazzy-ros2-control package and everything is ok now.

**Comment by AksonovSergei** [comment]
Дуже дякую.

**Comment by AksonovSergei** [comment]
I have added the ros-jazzy-ros2-control package as dapendecy to package.xml.
